"""Base Emulation Generator class for all Emulation Generators.
"""
from typing import Optional
from pyrox.models import plc
from pyrox.models import emu


class BaseEmulationGenerator(emu.EmulationGenerator):
    """Base class for emulation logic generators."""
    supporting_class = plc.Controller

    def __init__(
        self,
        controller: plc.Controller
    ) -> None:
        super().__init__(controller)

    @property
    def base_tags(self) -> list[tuple[str, str, str]]:
        """List of base tags common to all controllers.

        Returns:
            list[str]: List of tuples (tag_name, datatype, description)
        """
        return [
            ('zz_Demo3D_Uninhibit', 'INT', 'Uninhibit mode for the controller.'),
            ('zz_Demo3D_Inhibit', 'INT', 'Inhibit mode for the controller.'),
            ('zz_Demo3D_ToggleInhibit', 'BOOL', 'Toggle inhibit mode for the controller.'),
            ('zz_Demo3D_LocalMode', 'INT', 'Local mode for the controller.'),
            ('zz_Demo3D_TestMode', 'BOOL', 'Demo 3D\nEmulation Test Mode\n-----\nREMOVE IF FOUND IN PRODUCTION'),
        ]

    @property
    def custom_tags(self) -> list[tuple[str, str, str, Optional[str]]]:
        """List of custom tags specific to the controller type.

        Returns:
            list[str]: List of tuples (tag_name, datatype, description, dimensions).
        """
        raise NotImplementedError("Subclasses must implement custom_tags")

    @property
    def emulation_safety_routine_description(self) -> str:
        """Description for the safety routine to add emulation logic to.

        Returns:
            str: Description of the safety routine
        """
        return self.emulation_standard_routine_description

    @property
    def emulation_safety_routine_name(self) -> str:
        """Name of the safety routine to add emulation logic to.

        Returns:
            str: Name of the safety routine
        """
        return 'zzz_s_Emulation'

    @property
    def emulation_standard_routine_description(self) -> str:
        """Description for the standard routine to add emulation logic to.

        Returns:
            str: Description of the standard routine
        """
        return ''.join([
            'Emulation routine for automation controller.\n',
            'This routine is auto-generated by Indicon LLC.\n',
            'Do not modify.'
        ])

    @property
    def emulation_standard_routine_name(self) -> str:
        """Name of the standard routine to add emulation logic to.

        Returns:
            str: Name of the standard routine
        """
        return 'zzz_Emulation'

    @property
    def generator_object(self) -> plc.Controller:
        return self._generator_object

    @generator_object.setter
    def generator_object(self, value: plc.Controller):
        if value.__class__.__name__ != self.supporting_class:
            raise TypeError(f'Controller must be of type {self.supporting_class}, got {value.__class__.__name__} instead.')
        self._generator_object = value

    @property
    def target_safety_program_name(self) -> str:
        """Name of the safety program to add emulation logic to.

        Returns:
            str: Name of the safety program
        """
        raise NotImplementedError("Subclasses must implement target_safety_program_name")

    @property
    def target_standard_program_name(self) -> str:
        """Name of the standard program to add emulation logic to.

        Returns:
            str: Name of the standard program
        """
        raise NotImplementedError("Subclasses must implement target_standard_program_name")

    @property
    def test_mode_tag(self) -> str:
        """Name of the test mode tag.

        Returns:
            str: Name of the test mode tag
        """
        return self.base_tags[4][0]

    @property
    def toggle_inhibit_tag(self) -> str:
        """Name of the toggle inhibit tag.

        Returns:
            str: Name of the toggle inhibit tag
        """
        return self.base_tags[2][0]
