"""Meta data for EPlan projects and objects.
"""


# -------------- EPLAN Constants -----------------
EPLAN_PROJECT_ROOT = 'EplanPxfRoot'
EPLAN_UNKNOWN_ATTRIBUTE_DEFAULT = 'Unknown'

# -------------- EPLAN Property Keys -----------------
EPLAN_PROPERTY_KEY = 'P11'
EPLAN_PROJECT_INDEX_NUMBER_KEY = 'P49'
EPLAN_SHEET_OBJECTS_KEY = 'O3'
EPLAN_PROJECT_SHEET_KEY = 'O4'
EPLAN_PROJECT_GROUP_KEY = 'O6'
EPLAN_PROJECT_DATA_KEY = 'O14'
EPLAN_SHEET_TAGS_KEY = 'O17'
EPLAN_SHEET_TEXT_OBJECTS_KEY = 'O30'
EPLAN_SHEET_META_DATA_KEY = 'O52'
EPLAN_GRAPHIC_DATA_KEY = 'O76'
EPLAN_PROJECT_BOM_KEY = 'O117'
EPLAN_USER_SUPPL_DATA_KEY = 'O211'
EPLAN_USER_SUPPL_FIELD_KEY = 'S212x5'
EPLAN_FORM_PROPERTY_KEY = 'S75x5'

# -------------- EPLAN Meta Keys -----------------
EPLAN_PARENT_FORM_KEY = '@A22'  # Maybe?
EPLAN_LAST_EDIT_TIME_EPOCH_KEY = '@A48'
EPLAN_GROUP_NAME_KEY = '@A82'
EPLAN_PROJECT_TITLE_KEY = '@A133'
EPLAN_OBJECT_DETAIL_KEY = '@A511'
EPLAN_BOM_PART_NO_KEY = '@A1101'
EPLAN_PAGE_NUMBER_MAJOR_KEY = '@A1101'
EPLAN_PAGE_NUMBER_MINOR_KEY = '@A1102'
EPLAN_FORM_LAST_EDITED_BY_KEY = '@A1408'
EPLAN_FORM_DESCRIPTION_KEY = '@A1410'
EPLAN_FORM_TEMPLATE_NAME_KEY = '@A1413'
EPLAN_FORM_NAME_KEY = '@A2196'
EPLAN_GROUP_META_KEY = '@P1002'
EPLAN_DEVICE_IP_ADDRESS_KEY = '@P1009'
EPLAN_MAJOR_DEVICE_KEY = '@P1100'  # where symbol is "="XXXyyy
EPLAN_MINOR_DEVICE_KEY = '@P1200'  # where symbol is =XXXyyy"+"abc
EPLAN_PROJECT_STRUCT_FUNCTIONAL_ASSIGNMENT_KEY = '@P10001'
EPLAN_PROJECT_STRUCT_HIGHER_LEVEL_FUNCTION_KEY = '@P10002'
EPLAN_PROJECT_STRUCT_INSTALLATION_SITE_KEY = '@P10003'
EPLAN_PROJECT_STRUCT_MOUNTING_LOCATION_KEY = '@P10004'
EPLAN_PROJECT_NAME_FULL_KEY = '@P10009'
EPLAN_PROJECT_PATH_KEY = '@P10010'
EPLAN_PROJECT_DESCRIPTION_KEY = '@P10011'
EPLAN_USE_PAGE_NAME_IN_DT_KEY = '@P10012'
EPLAN_JOB_NUMBER_KEY = '@P10013'
EPLAN_COMPANY_NAME_KEY = '@P10015'
EPLAN_COMPANY_ADDRESS_LINE1_KEY = '@P10016'
EPLAN_COMPANY_ADDRESS_LINE2_KEY = '@P10017'
EPLAN_CREATOR_KEY = '@P10020'
EPLAN_CREATION_DATE_EPOCH_KEY = '@P10021'
EPLAN_LAST_EDITOR_KEY = '@P10022'
EPLAN_MODIFICATION_DATE_EPOCH_KEY = '@P10023'
EPLAN_DATE_KEY = '@P10027'
EPLAN_PLACE_OF_INSTALL_KEY = '@P10032'
EPLAN_LOCATION_KEY = '@P10035'
EPLAN_LAST_VERSION_USED_KEY = '@P10043'
EPLAN_PROJECT_PATH_FULL_KEY = '@P10045'
EPLAN_CREATION_TIME_KEY = '@P10046'
EPLAN_PROJECT_TEMPLATE_KEY = '@P10069'
EPLAN_APPROVED_BY_KEY = '@P10160'
EPLAN_CUSTOMER_CODE_KEY = '@P10180'
EPLAN_UNIQUE_PROJECT_ID_KEY = '@P10184'
EPLAN_LICENSE_DONGLE_ID_KEY = '@P10185'
EPLAN_NAME_KEY = '@P11011'
EPLAN_INDEX_MAJOR_KEY = '@P11012'
EPLAN_INDEX_MINOR_KEY = '@P11013'
EPLAN_TEMPLATE_FORM_NAME_KEY = '@P11015'
EPLAN_TITLE_BLOCK_KEY = '@P11016'
EPLAN_CREATED_BY_KEY = '@P11020'
EPLAN_CREATED_ON_EPOCH_KEY = '@P11021'
EPLAN_EDITED_BY_KEY = '@P11022'
EPLAN_EDITED_ON_EPOCH_KEY = '@P11023'
EPLAN_SUPPLY_FIELD_SHEET_NO_KEY = '@P11033'
EPLAN_PROJECT_NAME_KEY = '@P11056'
EPLAN_SPECIAL_REMARKS_KEY = '@P11059'
EPLAN_REFERENCED_OBJECTS_KEY = '@P11063'
EPLAN_SOURCE_KEY = '@P11066'
EPLAN_SOURCE_PROJECT_KEY = '@P11067'
EPLAN_BOM_QUANTITY_KEY = '@P2200'
EPLAN_BOM_ITEM_DUP_KEY = '@P22001'
EPLAN_BOM_SPEC_NO_KEY = '@P22002'
EPLAN_BOM_PART_NO_KEY = '@P22003'
EPLAN_BOM_PART_DESC_KEY = '@P22004'
EPLAN_BOM_CABLE_CONDUIT_COUNT_KEY = '@P22005'
EPLAN_BOM_CABLE_SIZE_LENGTH_KEY = '@P22006'
EPLAN_BOM_MANUFACTURER_KEY = '@P22007'
EPLAN_BOM_PART_ADDED_BY_FULL_KEY = '@P22901'
EPLAN_BOM_PART_EDITED_BY_FULL_KEY = '@P22902'
EPLAN_BOM_ADDED_BY_KEY = '@P22980'
EPLAN_BOM_ADDED_ON_EPOCH_KEY = '@P22981'
EPLAN_BOM_EDITED_BY_KEY = '@P22982'
EPLAN_BOM_EDITED_ON_EPOCH_KEY = '@P22983'

# -------------- EPLAN Key Map -----------------
# Mapping of EPLAN property keys to more user-friendly names
EPLAN_DICT_MAP = {
    EPLAN_APPROVED_BY_KEY: 'Approved By',
    EPLAN_BOM_ADDED_BY_KEY: 'BOM Added By',
    EPLAN_BOM_ADDED_ON_EPOCH_KEY: 'BOM Added On (Epoch)',
    EPLAN_BOM_CABLE_CONDUIT_COUNT_KEY: 'Cable/Conduit Count',
    EPLAN_BOM_CABLE_SIZE_LENGTH_KEY: 'Cable Size/Length',
    EPLAN_BOM_EDITED_BY_KEY: 'BOM Edited By',
    EPLAN_BOM_EDITED_ON_EPOCH_KEY: 'BOM Edited On (Epoch)',
    EPLAN_BOM_ITEM_DUP_KEY: 'BOM Item Dup',
    EPLAN_BOM_MANUFACTURER_KEY: 'Manufacturer',
    EPLAN_BOM_PART_NO_KEY: 'Part Number',
    EPLAN_BOM_PART_DESC_KEY: 'Part Description',
    EPLAN_BOM_QUANTITY_KEY: 'Quantity',
    EPLAN_BOM_SPEC_NO_KEY: 'BOM Spec No.',
    EPLAN_CREATED_BY_KEY: 'Created By',
    EPLAN_CREATED_ON_EPOCH_KEY: 'Created On (Epoch)',
    EPLAN_CREATION_DATE_EPOCH_KEY: 'Created On (Epoch)',
    EPLAN_CREATOR_KEY: 'Created By',
    EPLAN_COMPANY_ADDRESS_LINE1_KEY: 'Address Line 1',
    EPLAN_COMPANY_ADDRESS_LINE2_KEY: 'Address Line 2',
    EPLAN_CUSTOMER_CODE_KEY: 'Project Number',
    EPLAN_DEVICE_IP_ADDRESS_KEY: 'IP Address',
    EPLAN_EDITED_BY_KEY: 'Edit By',
    EPLAN_EDITED_ON_EPOCH_KEY: 'Edited On (Epoch)',
    EPLAN_FORM_DESCRIPTION_KEY: 'Description',
    EPLAN_FORM_LAST_EDITED_BY_KEY: 'Last Edited By',
    EPLAN_FORM_NAME_KEY: 'Form Name',
    EPLAN_FORM_PROPERTY_KEY: 'Form Properties',
    EPLAN_FORM_TEMPLATE_NAME_KEY: 'Form Template Name',
    EPLAN_GRAPHIC_DATA_KEY: 'Graphic Meta Data',
    EPLAN_GROUP_NAME_KEY: 'Group Name',
    EPLAN_GROUP_META_KEY: 'Group Meta Data',
    EPLAN_INDEX_MAJOR_KEY: 'Major Index',
    EPLAN_INDEX_MINOR_KEY: 'Minor Index',
    EPLAN_JOB_NUMBER_KEY: 'Job Number',
    EPLAN_LAST_EDIT_TIME_EPOCH_KEY: 'Last Edit Time (Epoch)',
    EPLAN_MAJOR_DEVICE_KEY: 'Device Major Relation',
    EPLAN_MINOR_DEVICE_KEY: 'Device Minor Relation',
    EPLAN_NAME_KEY: 'Name',
    EPLAN_OBJECT_DETAIL_KEY: 'Object Detail',
    EPLAN_PAGE_NUMBER_MAJOR_KEY: 'Page Number Major',
    EPLAN_PAGE_NUMBER_MINOR_KEY: 'Page Number Minor',
    EPLAN_PARENT_FORM_KEY: 'Parent Form',
    EPLAN_PROJECT_BOM_KEY: 'Project BOM',
    EPLAN_PROJECT_DATA_KEY: 'Project Data',
    EPLAN_COMPANY_NAME_KEY: 'Company Name',
    EPLAN_LOCATION_KEY: 'Location',
    EPLAN_PLACE_OF_INSTALL_KEY: 'Place Of Installation',
    EPLAN_PROJECT_DESCRIPTION_KEY: 'Project Description',
    EPLAN_PROJECT_GROUP_KEY: 'Project Groups',
    EPLAN_PROJECT_INDEX_NUMBER_KEY: 'Indexes',
    EPLAN_PROJECT_NAME_KEY: 'Project Name',
    EPLAN_PROJECT_NAME_FULL_KEY: 'Project Name Full',
    EPLAN_PROJECT_PATH_KEY: 'Project Path',
    EPLAN_PROJECT_PATH_FULL_KEY: 'Project Path Full',
    EPLAN_PROJECT_STRUCT_FUNCTIONAL_ASSIGNMENT_KEY: 'Functional Assignment',
    EPLAN_PROJECT_STRUCT_HIGHER_LEVEL_FUNCTION_KEY: 'Higher Level Function',
    EPLAN_PROJECT_STRUCT_INSTALLATION_SITE_KEY: 'Installation Site',
    EPLAN_PROJECT_STRUCT_MOUNTING_LOCATION_KEY: 'Mounting Location',
    EPLAN_PROJECT_SHEET_KEY: 'Sheets',
    EPLAN_PROJECT_TEMPLATE_KEY: 'Project Template',
    EPLAN_PROJECT_TITLE_KEY: 'Project Title',
    EPLAN_PROPERTY_KEY: 'Properties',
    EPLAN_SHEET_META_DATA_KEY: 'Sheet Meta Data',
    EPLAN_SHEET_OBJECTS_KEY: 'Sheet Objects',
    EPLAN_SHEET_TAGS_KEY: 'Sheet Tags',
    EPLAN_SHEET_TEXT_OBJECTS_KEY: 'Sheet Text Objects',
    EPLAN_SOURCE_KEY: 'Source',
    EPLAN_SOURCE_PROJECT_KEY: 'Report: Source Project',
    EPLAN_SPECIAL_REMARKS_KEY: 'Special Remarks',
    EPLAN_SUPPLY_FIELD_SHEET_NO_KEY: 'Supply Field Sheet No.',
    EPLAN_TEMPLATE_FORM_NAME_KEY: 'Template Form Name',
    EPLAN_TITLE_BLOCK_KEY: 'Title Block',
    EPLAN_UNIQUE_PROJECT_ID_KEY: 'Unique Project ID',
    EPLAN_USE_PAGE_NAME_IN_DT_KEY: 'Use Page Name In DT',
    EPLAN_USER_SUPPL_DATA_KEY: 'User Supplimental Data',
    EPLAN_USER_SUPPL_FIELD_KEY: 'User Supplimental Field',
}
