"""Meta data for EPlan projects and objects.
"""


# -------------- EPLAN Constants -----------------
EPLAN_PROJECT_ROOT = 'EplanPxfRoot'
EPLAN_UNKNOWN_ATTRIBUTE_DEFAULT = 'Unknown'

# -------------- EPLAN Property Keys -----------------
EPLAN_PROPERTY_KEY = 'P11'
EPLAN_PROJECT_INDEX_NUMBER_KEY = 'P49'
EPLAN_SHEET_OBJECTS_KEY = 'O3'
EPLAN_PROJECT_SHEET_KEY = 'O4'
EPLAN_PROJECT_GROUP_KEY = 'O6'
EPLAN_PROJECT_DATA_KEY = 'O14'
EPLAN_SHEET_TAGS_KEY = 'O17'
EPLAN_SHEET_TEXT_OBJECTS_KEY = 'O30'
EPLAN_SHEET_META_DATA_KEY = 'O52'
EPLAN_GRAPHIC_DATA_KEY = 'O76'
EPLAN_PROJECT_BOM_KEY = 'O117'
EPLAN_USER_SUPPL_DATA_KEY = 'O211'
EPLAN_USER_SUPPL_FIELD_KEY = 'S212x5'
EPLAN_FORM_PROPERTY_KEY = 'S75x5'

# -------------- EPLAN Meta Keys -----------------
EPLAN_PARENT_FORM_KEY = '@A22'  # Maybe?
EPLAN_LAST_EDIT_TIME_EPOCH_KEY = '@A48'
EPLAN_GROUP_NAME_KEY = '@A82'
EPLAN_PROJECT_TITLE_KEY = '@A133'
EPLAN_OBJECT_DETAIL_KEY = '@A511'
EPLAN_BOM_PART_NO_KEY = '@A1101'
EPLAN_PAGE_NUMBER_MAJOR_KEY = '@A1101'  # Note: Same as BOM_PART_NO - may need different value
EPLAN_PAGE_NUMBER_MINOR_KEY = '@A1102'
EPLAN_FORM_LAST_EDITED_BY_KEY = '@A1408'
EPLAN_FORM_DESCRIPTION_KEY = '@A1410'
EPLAN_FORM_TEMPLATE_NAME_KEY = '@A1413'
EPLAN_FORM_NAME_KEY = '@A2196'
EPLAN_GROUP_META_KEY = '@P1002'
EPLAN_DEVICE_IP_ADDRESS_KEY = '@P1009'
EPLAN_MAJOR_DEVICE_KEY = '@P1100'  # where symbol is "="XXXyyy
EPLAN_MINOR_DEVICE_KEY = '@P1200'  # where symbol is =XXXyyy"+"abc
EPLAN_PROJECT_STRUCT_FUNCTIONAL_ASSIGNMENT_KEY = '@P10001'
EPLAN_PROJECT_STRUCT_HIGHER_LEVEL_FUNCTION_KEY = '@P10002'
EPLAN_PROJECT_STRUCT_INSTALLATION_SITE_KEY = '@P10003'
EPLAN_PROJECT_STRUCT_MOUNTING_LOCATION_KEY = '@P10004'
EPLAN_PROJECT_NAME_FULL_KEY = '@P10009'
EPLAN_PROJECT_PATH_KEY = '@P10010'
EPLAN_PROJECT_DESCRIPTION_KEY = '@P10011'
EPLAN_USE_PAGE_NAME_IN_DT_KEY = '@P10012'
EPLAN_JOB_NUMBER_KEY = '@P10013'
EPLAN_COMPANY_NAME_KEY = '@P10015'
EPLAN_COMPANY_ADDRESS_LINE1_KEY = '@P10016'
EPLAN_COMPANY_ADDRESS_LINE2_KEY = '@P10017'
EPLAN_CREATOR_KEY = '@P10020'
EPLAN_CREATION_DATE_EPOCH_KEY = '@P10021'
EPLAN_LAST_EDITOR_KEY = '@P10022'
EPLAN_MODIFICATION_DATE_EPOCH_KEY = '@P10023'
EPLAN_DATE_KEY = '@P10027'
EPLAN_PLACE_OF_INSTALL_KEY = '@P10032'
EPLAN_LOCATION_KEY = '@P10035'
EPLAN_LAST_VERSION_USED_KEY = '@P10043'
EPLAN_PROJECT_PATH_FULL_KEY = '@P10045'
EPLAN_CREATION_TIME_KEY = '@P10046'
EPLAN_PROJECT_TEMPLATE_KEY = '@P10069'
EPLAN_APPROVED_BY_KEY = '@P10160'
EPLAN_CUSTOMER_CODE_KEY = '@P10180'
EPLAN_UNIQUE_PROJECT_ID_KEY = '@P10184'
EPLAN_LICENSE_DONGLE_ID_KEY = '@P10185'
EPLAN_NAME_KEY = '@P11011'
EPLAN_INDEX_MAJOR_KEY = '@P11012'
EPLAN_INDEX_MINOR_KEY = '@P11013'
EPLAN_TEMPLATE_FORM_NAME_KEY = '@P11015'
EPLAN_TITLE_BLOCK_KEY = '@P11016'
EPLAN_CREATED_BY_KEY = '@P11020'
EPLAN_CREATED_ON_EPOCH_KEY = '@P11021'
EPLAN_EDITED_BY_KEY = '@P11022'
EPLAN_EDITED_ON_EPOCH_KEY = '@P11023'
EPLAN_SUPPLY_FIELD_SHEET_NO_KEY = '@P11033'
EPLAN_PROJECT_NAME_KEY = '@P11056'
EPLAN_SPECIAL_REMARKS_KEY = '@P11059'
EPLAN_REFERENCED_OBJECTS_KEY = '@P11063'
EPLAN_SOURCE_KEY = '@P11066'
EPLAN_SOURCE_PROJECT_KEY = '@P11067'
EPLAN_BOM_QUANTITY_KEY = '@P2200'
EPLAN_BOM_ITEM_DUP_KEY = '@P22001'
EPLAN_BOM_SPEC_NO_KEY = '@P22002'
EPLAN_BOM_PART_NO_KEY = '@P22003'
EPLAN_BOM_PART_DESC_KEY = '@P22004'
EPLAN_BOM_CABLE_CONDUIT_COUNT_KEY = '@P22005'
EPLAN_BOM_CABLE_SIZE_LENGTH_KEY = '@P22006'
EPLAN_BOM_MANUFACTURER_KEY = '@P22007'
EPLAN_BOM_PART_ADDED_BY_FULL_KEY = '@P22901'
EPLAN_BOM_PART_EDITED_BY_FULL_KEY = '@P22902'
EPLAN_BOM_ADDED_BY_KEY = '@P22980'
EPLAN_BOM_ADDED_ON_EPOCH_KEY = '@P22981'
EPLAN_BOM_EDITED_BY_KEY = '@P22982'
EPLAN_BOM_EDITED_ON_EPOCH_KEY = '@P22983'

# -------------- Additional Device Property Keys -----------------
EPLAN_DEVICE_DESIGNATION_KEY = 'P20011'
EPLAN_DEVICE_TYPE_KEY = 'P20049'
EPLAN_DEVICE_SUBTYPE_KEY = 'P20050'
EPLAN_DEVICE_VARIANT_KEY = 'P20051'
EPLAN_DEVICE_STATUS_FLAG_KEY = 'P20094'
EPLAN_DEVICE_PARAMETER_KEY = 'P20216'
EPLAN_DEVICE_TAG_KEY = 'P20400'
EPLAN_DEVICE_EXTERNAL_FILE_KEY = 'P20468'
EPLAN_DEVICE_CONFIG_FLAG_KEY = 'P31030'

# -------------- Additional BOM Property Keys -----------------
EPLAN_BOM_SEQUENCE_NUMBER_KEY = '@P22042'
EPLAN_BOM_CALCULATION_FLAG_KEY = '@P22046'
EPLAN_BOM_QUANTITY_CALC_KEY = '@P22122'
EPLAN_BOM_INCLUSION_FLAG_KEY = '@P22131'
EPLAN_BOM_VALIDATION_FLAG_KEY = '@P22138'

# -------------- Object Display Property Keys -----------------
EPLAN_OBJECT_X_POSITION_KEY = 'A404'
EPLAN_OBJECT_Y_POSITION_KEY = 'A405'
EPLAN_OBJECT_WIDTH_KEY = 'A406'
EPLAN_OBJECT_HEIGHT_KEY = 'A407'
EPLAN_OBJECT_DISPLAY_WIDTH_KEY = 'A411'
EPLAN_OBJECT_ALIGNMENT_L_KEY = 'A412'
EPLAN_OBJECT_ALIGNMENT_T_KEY = 'A413'
EPLAN_OBJECT_ALIGNMENT_R_KEY = 'A414'
EPLAN_OBJECT_ALIGNMENT_B_KEY = 'A415'
EPLAN_OBJECT_ROTATION_KEY = 'A416'
EPLAN_OBJECT_REFERENCE_KEY = 'A501'
EPLAN_OBJECT_LINK_TYPE_KEY = 'A503'
EPLAN_OBJECT_LINK_TARGET_KEY = 'A506'
EPLAN_OBJECT_DISPLAY_TYPE_KEY = 'A941'
EPLAN_OBJECT_DISPLAY_FLAG_KEY = 'A942'
EPLAN_OBJECT_LAYER_KEY = 'A943'
EPLAN_OBJECT_Z_ORDER_KEY = 'A944'
EPLAN_OBJECT_VISIBLE_KEY = 'A945'
EPLAN_OBJECT_LOCKED_KEY = 'A946'
EPLAN_OBJECT_SELECTABLE_KEY = 'A947'
EPLAN_OBJECT_TEXT_SIZE_KEY = 'A949'
EPLAN_OBJECT_TEXT_CONTENT_KEY = 'A950'

# -------------- Graphics and Symbol Property Keys -----------------
EPLAN_GRAPHICS_ENABLED_KEY = 'A1422'
EPLAN_GRAPHICS_VISIBLE_KEY = 'A1423'
EPLAN_GRAPHICS_NAME_KEY = 'A1424'
EPLAN_GRAPHICS_PATH_KEY = 'A1425'
EPLAN_GRAPHICS_ID_KEY = 'A1426'
EPLAN_GRAPHICS_TYPE_KEY = 'A1427'
EPLAN_GRAPHICS_COLOR_KEY = 'A1428'
EPLAN_GRAPHICS_LINE_WIDTH_KEY = 'A1429'
EPLAN_GRAPHICS_LINE_TYPE_KEY = 'A1430'
EPLAN_GRAPHICS_FILL_KEY = 'A1433'
EPLAN_GRAPHICS_PATTERN_KEY = 'A1434'
EPLAN_GRAPHICS_STYLE_KEY = 'A1435'

# -------------- Line and Drawing Property Keys -----------------
EPLAN_LINE_WIDTH_KEY = 'A961'
EPLAN_LINE_COLOR_R_KEY = 'A962'
EPLAN_LINE_COLOR_G_KEY = 'A963'
EPLAN_LINE_COLOR_B_KEY = 'A964'
EPLAN_LINE_COLOR_A_KEY = 'A965'
EPLAN_LINE_TYPE_CODE_KEY = 'A966'
EPLAN_LINE_PATTERN_KEY = 'A967'
EPLAN_LINE_START_CAP_KEY = 'A968'
EPLAN_LINE_END_CAP_KEY = 'A969'

# -------------- Advanced Object Property Keys -----------------
EPLAN_OBJECT_SCALE_KEY = 'A4000'
EPLAN_OBJECT_ANGLE_KEY = 'A4001'
EPLAN_OBJECT_MIRROR_KEY = 'A4013'
EPLAN_OBJECT_TEXT_FIELD_KEY = 'A4017'
EPLAN_OBJECT_MAX_VALUE_KEY = 'A4019'
EPLAN_OBJECT_MIN_VALUE_KEY = 'A4020'
EPLAN_OBJECT_PARENT_REF_KEY = 'A4051'
EPLAN_OBJECT_CHILD_REF_KEY = 'A4052'
EPLAN_OBJECT_STATE_FLAGS_KEY = 'A4064'

# -------------- Critical Missing Keys from Live Data Analysis -----------------
# Most frequently used keys in actual EPLAN projects

# Project Structure and Identification Keys
EPLAN_PROJECT_ID_KEY = '@P10000'
EPLAN_OBJECT_ID_KEY = '@A1'
EPLAN_OBJECT_BUILD_FLAG_KEY = '@A3'
EPLAN_OBJECT_STATE_PRIMARY_KEY = '@A13'
EPLAN_OBJECT_STATE_SECONDARY_KEY = '@A14'
EPLAN_EPLAN_VERSION_KEY = '@A134'
EPLAN_PROJECT_VERSION_KEY = '@A135'

# Advanced Project Properties
EPLAN_PROJECT_CONFIG_FLAGS_KEY = '@P10018'
EPLAN_PROJECT_CONFIG_BINARY_KEY = '@P10019'
EPLAN_PROJECT_SETTINGS_KEY = '@P10029'
EPLAN_PROJECT_STRUCTURE_L1_KEY = '@P10050'
EPLAN_PROJECT_STRUCTURE_L2_KEY = '@P10051'
EPLAN_PROJECT_STRUCTURE_L3_KEY = '@P10053'
EPLAN_PROJECT_STRUCTURE_L4_KEY = '@P10054'
EPLAN_PROJECT_STRUCTURE_L5_KEY = '@P10055'
EPLAN_PROJECT_STRUCTURE_L6_KEY = '@P10056'
EPLAN_PROJECT_STRUCTURE_L7_KEY = '@P10057'
EPLAN_PROJECT_STRUCTURE_L8_KEY = '@P10059'
EPLAN_PROJECT_STRUCTURE_L9_KEY = '@P10060'
EPLAN_PROJECT_STRUCTURE_L10_KEY = '@P10061'
EPLAN_PROJECT_STRUCTURE_L11_KEY = '@P10062'

# Additional Object Types
EPLAN_OBJECT_TYPE_116_KEY = 'O116'
EPLAN_OBJECT_TYPE_155_KEY = 'O155'
EPLAN_OBJECT_TYPE_219_KEY = 'O219'
EPLAN_OBJECT_TYPE_256_KEY = 'O256'

# Additional Section Definitions
EPLAN_SECTION_167_FIELD_KEY = 'S167x5'
EPLAN_SECTION_39_DEFINITION_KEY = 'S39x761'
EPLAN_SECTION_40_DEFINITION_KEY = 'S40x21'
EPLAN_SECTION_54_PROPERTIES_KEY = 'S54x505'

# Form and Page Attribute Keys (High Frequency)
EPLAN_FORM_ATTRIBUTE_1402_KEY = '@A1402'
EPLAN_FORM_ATTRIBUTE_1403_KEY = '@A1403'
EPLAN_FORM_ATTRIBUTE_1404_KEY = '@A1404'
EPLAN_FORM_ATTRIBUTE_1405_KEY = '@A1405'
EPLAN_FORM_ATTRIBUTE_1406_KEY = '@A1406'
EPLAN_FORM_ATTRIBUTE_1407_KEY = '@A1407'
EPLAN_FORM_ATTRIBUTE_1409_KEY = '@A1409'
EPLAN_FORM_ATTRIBUTE_1411_KEY = '@A1411'
EPLAN_FORM_ATTRIBUTE_1412_KEY = '@A1412'
EPLAN_FORM_ATTRIBUTE_1414_KEY = '@A1414'
EPLAN_FORM_ATTRIBUTE_1415_KEY = '@A1415'
EPLAN_FORM_ATTRIBUTE_1416_KEY = '@A1416'
EPLAN_FORM_ATTRIBUTE_1417_KEY = '@A1417'
EPLAN_FORM_ATTRIBUTE_1418_KEY = '@A1418'

# High-priority missing attribute keys from live data
EPLAN_ATTRIBUTE_1001_KEY = '@A1001'
EPLAN_ATTRIBUTE_1101_KEY = '@A1101'
EPLAN_ATTRIBUTE_1105_KEY = '@A1105'
EPLAN_ATTRIBUTE_1106_KEY = '@A1106'
EPLAN_ATTRIBUTE_1108_KEY = '@A1108'
EPLAN_ATTRIBUTE_1306_KEY = '@A1306'
EPLAN_ATTRIBUTE_1308_KEY = '@A1308'
EPLAN_ATTRIBUTE_1317_KEY = '@A1317'
EPLAN_ATTRIBUTE_1331_KEY = '@A1331'
EPLAN_ATTRIBUTE_1348_KEY = '@A1348'
EPLAN_ATTRIBUTE_1351_KEY = '@A1351'
EPLAN_ATTRIBUTE_1352_KEY = '@A1352'
EPLAN_ATTRIBUTE_1355_KEY = '@A1355'
EPLAN_ATTRIBUTE_1356_KEY = '@A1356'
EPLAN_ATTRIBUTE_1357_KEY = '@A1357'
EPLAN_ATTRIBUTE_1358_KEY = '@A1358'
EPLAN_ATTRIBUTE_1359_KEY = '@A1359'
EPLAN_ATTRIBUTE_1365_KEY = '@A1365'
EPLAN_ATTRIBUTE_1366_KEY = '@A1366'
EPLAN_ATTRIBUTE_1367_KEY = '@A1367'
EPLAN_ATTRIBUTE_1368_KEY = '@A1368'
EPLAN_ATTRIBUTE_1370_KEY = '@A1370'
EPLAN_ATTRIBUTE_1380_KEY = '@A1380'
EPLAN_ATTRIBUTE_1381_KEY = '@A1381'
EPLAN_ATTRIBUTE_1383_KEY = '@A1383'

# Additional high-usage property keys
EPLAN_PROPERTY_10002_KEY = '@P10002'
EPLAN_PROPERTY_10003_KEY = '@P10003'
EPLAN_PROPERTY_10010_KEY = '@P10010'
EPLAN_PROPERTY_10011_KEY = '@P10011'
EPLAN_PROPERTY_10012_KEY = '@P10012'
EPLAN_PROPERTY_10013_KEY = '@P10013'
EPLAN_PROPERTY_10014_KEY = '@P10014'
EPLAN_PROPERTY_10015_KEY = '@P10015'
EPLAN_PROPERTY_10016_KEY = '@P10016'
EPLAN_PROPERTY_10017_KEY = '@P10017'

# -------------- Field Definition Keys -----------------
EPLAN_GRAPHICS_FIELD_DEF_KEY = 'S54x1432'

# -------------- EPLAN Key Map -----------------
# Mapping of EPLAN property keys to more user-friendly names
EPLAN_DICT_MAP = {
    EPLAN_APPROVED_BY_KEY: 'Approved By',
    EPLAN_BOM_ADDED_BY_KEY: 'BOM Added By',
    EPLAN_BOM_ADDED_ON_EPOCH_KEY: 'BOM Added On (Epoch)',
    EPLAN_BOM_CABLE_CONDUIT_COUNT_KEY: 'Cable/Conduit Count',
    EPLAN_BOM_CABLE_SIZE_LENGTH_KEY: 'Cable Size/Length',
    EPLAN_BOM_EDITED_BY_KEY: 'BOM Edited By',
    EPLAN_BOM_EDITED_ON_EPOCH_KEY: 'BOM Edited On (Epoch)',
    EPLAN_BOM_ITEM_DUP_KEY: 'BOM Item Dup',
    EPLAN_BOM_MANUFACTURER_KEY: 'Manufacturer',
    EPLAN_BOM_PART_NO_KEY: 'Part Number',
    EPLAN_BOM_PART_DESC_KEY: 'Part Description',
    EPLAN_BOM_QUANTITY_KEY: 'Quantity',
    EPLAN_BOM_SPEC_NO_KEY: 'BOM Spec No.',
    EPLAN_CREATED_BY_KEY: 'Created By',
    EPLAN_CREATED_ON_EPOCH_KEY: 'Created On (Epoch)',
    EPLAN_CREATION_DATE_EPOCH_KEY: 'Created On (Epoch)',
    EPLAN_CREATOR_KEY: 'Created By',
    EPLAN_COMPANY_ADDRESS_LINE1_KEY: 'Address Line 1',
    EPLAN_COMPANY_ADDRESS_LINE2_KEY: 'Address Line 2',
    EPLAN_CUSTOMER_CODE_KEY: 'Project Number',
    EPLAN_DEVICE_IP_ADDRESS_KEY: 'IP Address',
    EPLAN_EDITED_BY_KEY: 'Edit By',
    EPLAN_EDITED_ON_EPOCH_KEY: 'Edited On (Epoch)',
    EPLAN_FORM_DESCRIPTION_KEY: 'Description',
    EPLAN_FORM_LAST_EDITED_BY_KEY: 'Last Edited By',
    EPLAN_FORM_NAME_KEY: 'Form Name',
    EPLAN_FORM_PROPERTY_KEY: 'Form Properties',
    EPLAN_FORM_TEMPLATE_NAME_KEY: 'Form Template Name',
    EPLAN_GRAPHIC_DATA_KEY: 'Graphic Meta Data',
    EPLAN_GROUP_NAME_KEY: 'Group Name',
    EPLAN_GROUP_META_KEY: 'Group Meta Data',
    EPLAN_INDEX_MAJOR_KEY: 'Major Index',
    EPLAN_INDEX_MINOR_KEY: 'Minor Index',
    EPLAN_JOB_NUMBER_KEY: 'Job Number',
    EPLAN_LAST_EDIT_TIME_EPOCH_KEY: 'Last Edit Time (Epoch)',
    EPLAN_MAJOR_DEVICE_KEY: 'Device Major Relation',
    EPLAN_MINOR_DEVICE_KEY: 'Device Minor Relation',
    EPLAN_NAME_KEY: 'Name',
    EPLAN_OBJECT_DETAIL_KEY: 'Object Detail',
    EPLAN_PAGE_NUMBER_MAJOR_KEY: 'Page Number Major',
    EPLAN_PAGE_NUMBER_MINOR_KEY: 'Page Number Minor',
    EPLAN_PARENT_FORM_KEY: 'Parent Form',
    EPLAN_PROJECT_BOM_KEY: 'Project BOM',
    EPLAN_PROJECT_DATA_KEY: 'Project Data',
    EPLAN_COMPANY_NAME_KEY: 'Company Name',
    EPLAN_LOCATION_KEY: 'Location',
    EPLAN_PLACE_OF_INSTALL_KEY: 'Place Of Installation',
    EPLAN_PROJECT_DESCRIPTION_KEY: 'Project Description',
    EPLAN_PROJECT_GROUP_KEY: 'Project Groups',
    EPLAN_PROJECT_INDEX_NUMBER_KEY: 'Indexes',
    EPLAN_PROJECT_NAME_KEY: 'Project Name',
    EPLAN_PROJECT_NAME_FULL_KEY: 'Project Name Full',
    EPLAN_PROJECT_PATH_KEY: 'Project Path',
    EPLAN_PROJECT_PATH_FULL_KEY: 'Project Path Full',
    EPLAN_PROJECT_STRUCT_FUNCTIONAL_ASSIGNMENT_KEY: 'Functional Assignment',
    EPLAN_PROJECT_STRUCT_HIGHER_LEVEL_FUNCTION_KEY: 'Higher Level Function',
    EPLAN_PROJECT_STRUCT_INSTALLATION_SITE_KEY: 'Installation Site',
    EPLAN_PROJECT_STRUCT_MOUNTING_LOCATION_KEY: 'Mounting Location',
    EPLAN_PROJECT_SHEET_KEY: 'Sheets',
    EPLAN_PROJECT_TEMPLATE_KEY: 'Project Template',
    EPLAN_PROJECT_TITLE_KEY: 'Project Title',
    EPLAN_PROPERTY_KEY: 'Properties',
    EPLAN_SHEET_META_DATA_KEY: 'Sheet Meta Data',
    EPLAN_SHEET_OBJECTS_KEY: 'Sheet Objects',
    EPLAN_SHEET_TAGS_KEY: 'Sheet Tags',
    EPLAN_SHEET_TEXT_OBJECTS_KEY: 'Sheet Text Objects',
    EPLAN_SOURCE_KEY: 'Source',
    EPLAN_SOURCE_PROJECT_KEY: 'Report: Source Project',
    EPLAN_SPECIAL_REMARKS_KEY: 'Special Remarks',
    EPLAN_SUPPLY_FIELD_SHEET_NO_KEY: 'Supply Field Sheet No.',
    EPLAN_TEMPLATE_FORM_NAME_KEY: 'Template Form Name',
    EPLAN_TITLE_BLOCK_KEY: 'Title Block',
    EPLAN_UNIQUE_PROJECT_ID_KEY: 'Unique Project ID',
    EPLAN_USE_PAGE_NAME_IN_DT_KEY: 'Use Page Name In DT',
    EPLAN_USER_SUPPL_DATA_KEY: 'User Supplimental Data',
    EPLAN_USER_SUPPL_FIELD_KEY: 'User Supplimental Field',

    # Device Properties
    EPLAN_DEVICE_DESIGNATION_KEY: 'Device Designation',
    EPLAN_DEVICE_TYPE_KEY: 'Device Type',
    EPLAN_DEVICE_SUBTYPE_KEY: 'Device Subtype',
    EPLAN_DEVICE_VARIANT_KEY: 'Device Variant',
    EPLAN_DEVICE_STATUS_FLAG_KEY: 'Device Status Flag',
    EPLAN_DEVICE_PARAMETER_KEY: 'Device Parameter',
    EPLAN_DEVICE_TAG_KEY: 'Device Tag/Identifier',
    EPLAN_DEVICE_EXTERNAL_FILE_KEY: 'External File Reference',
    EPLAN_DEVICE_CONFIG_FLAG_KEY: 'Device Configuration Flag',

    # Additional BOM Properties
    EPLAN_BOM_SEQUENCE_NUMBER_KEY: 'BOM Sequence Number',
    EPLAN_BOM_CALCULATION_FLAG_KEY: 'BOM Calculation Flag',
    EPLAN_BOM_QUANTITY_CALC_KEY: 'BOM Quantity Calculation',
    EPLAN_BOM_INCLUSION_FLAG_KEY: 'BOM Inclusion Flag',
    EPLAN_BOM_VALIDATION_FLAG_KEY: 'BOM Validation Flag',

    # Object Display Properties
    EPLAN_OBJECT_X_POSITION_KEY: 'Object X Position',
    EPLAN_OBJECT_Y_POSITION_KEY: 'Object Y Position',
    EPLAN_OBJECT_WIDTH_KEY: 'Object Width',
    EPLAN_OBJECT_HEIGHT_KEY: 'Object Height',
    EPLAN_OBJECT_DISPLAY_WIDTH_KEY: 'Object Display Width',
    EPLAN_OBJECT_ALIGNMENT_L_KEY: 'Object Left Alignment',
    EPLAN_OBJECT_ALIGNMENT_T_KEY: 'Object Top Alignment',
    EPLAN_OBJECT_ALIGNMENT_R_KEY: 'Object Right Alignment',
    EPLAN_OBJECT_ALIGNMENT_B_KEY: 'Object Bottom Alignment',
    EPLAN_OBJECT_ROTATION_KEY: 'Object Rotation',
    EPLAN_OBJECT_REFERENCE_KEY: 'Object Reference',
    EPLAN_OBJECT_LINK_TYPE_KEY: 'Object Link Type',
    EPLAN_OBJECT_LINK_TARGET_KEY: 'Object Link Target',
    EPLAN_OBJECT_DISPLAY_TYPE_KEY: 'Object Display Type',
    EPLAN_OBJECT_DISPLAY_FLAG_KEY: 'Object Display Flag',
    EPLAN_OBJECT_LAYER_KEY: 'Object Layer',
    EPLAN_OBJECT_Z_ORDER_KEY: 'Object Z-Order',
    EPLAN_OBJECT_VISIBLE_KEY: 'Object Visible',
    EPLAN_OBJECT_LOCKED_KEY: 'Object Locked',
    EPLAN_OBJECT_SELECTABLE_KEY: 'Object Selectable',
    EPLAN_OBJECT_TEXT_SIZE_KEY: 'Object Text Size',
    EPLAN_OBJECT_TEXT_CONTENT_KEY: 'Object Text Content',

    # Graphics and Symbol Properties
    EPLAN_GRAPHICS_ENABLED_KEY: 'Graphics Enabled',
    EPLAN_GRAPHICS_VISIBLE_KEY: 'Graphics Visible',
    EPLAN_GRAPHICS_NAME_KEY: 'Graphics Name',
    EPLAN_GRAPHICS_PATH_KEY: 'Graphics Path',
    EPLAN_GRAPHICS_ID_KEY: 'Graphics ID',
    EPLAN_GRAPHICS_TYPE_KEY: 'Graphics Type',
    EPLAN_GRAPHICS_COLOR_KEY: 'Graphics Color',
    EPLAN_GRAPHICS_LINE_WIDTH_KEY: 'Graphics Line Width',
    EPLAN_GRAPHICS_LINE_TYPE_KEY: 'Graphics Line Type',
    EPLAN_GRAPHICS_FILL_KEY: 'Graphics Fill',
    EPLAN_GRAPHICS_PATTERN_KEY: 'Graphics Pattern',
    EPLAN_GRAPHICS_STYLE_KEY: 'Graphics Style',

    # Line and Drawing Properties
    EPLAN_LINE_WIDTH_KEY: 'Line Width',
    EPLAN_LINE_COLOR_R_KEY: 'Line Color Red',
    EPLAN_LINE_COLOR_G_KEY: 'Line Color Green',
    EPLAN_LINE_COLOR_B_KEY: 'Line Color Blue',
    EPLAN_LINE_COLOR_A_KEY: 'Line Color Alpha',
    EPLAN_LINE_TYPE_CODE_KEY: 'Line Type Code',
    EPLAN_LINE_PATTERN_KEY: 'Line Pattern',
    EPLAN_LINE_START_CAP_KEY: 'Line Start Cap',
    EPLAN_LINE_END_CAP_KEY: 'Line End Cap',

    # Advanced Object Properties
    EPLAN_OBJECT_SCALE_KEY: 'Object Scale',
    EPLAN_OBJECT_ANGLE_KEY: 'Object Angle',
    EPLAN_OBJECT_MIRROR_KEY: 'Object Mirror',
    EPLAN_OBJECT_TEXT_FIELD_KEY: 'Object Text Field',
    EPLAN_OBJECT_MAX_VALUE_KEY: 'Object Max Value',
    EPLAN_OBJECT_MIN_VALUE_KEY: 'Object Min Value',
    EPLAN_OBJECT_PARENT_REF_KEY: 'Object Parent Reference',
    EPLAN_OBJECT_CHILD_REF_KEY: 'Object Child Reference',
    EPLAN_OBJECT_STATE_FLAGS_KEY: 'Object State Flags',

    # Field Definitions
    EPLAN_GRAPHICS_FIELD_DEF_KEY: 'Graphics Field Definition',

    # Critical Live Data Keys
    EPLAN_PROJECT_ID_KEY: 'Project Identifier',
    EPLAN_OBJECT_ID_KEY: 'Object Reference ID',
    EPLAN_OBJECT_BUILD_FLAG_KEY: 'Object Build Flag',
    EPLAN_OBJECT_STATE_PRIMARY_KEY: 'Object Primary State',
    EPLAN_OBJECT_STATE_SECONDARY_KEY: 'Object Secondary State',
    EPLAN_EPLAN_VERSION_KEY: 'EPLAN Version',
    EPLAN_PROJECT_VERSION_KEY: 'Project Version',

    # Project Configuration
    EPLAN_PROJECT_CONFIG_FLAGS_KEY: 'Project Configuration Flags',
    EPLAN_PROJECT_CONFIG_BINARY_KEY: 'Project Binary Configuration',
    EPLAN_PROJECT_SETTINGS_KEY: 'Project Settings',
    EPLAN_PROJECT_STRUCTURE_L1_KEY: 'Project Structure Level 1',
    EPLAN_PROJECT_STRUCTURE_L2_KEY: 'Project Structure Level 2',
    EPLAN_PROJECT_STRUCTURE_L3_KEY: 'Project Structure Level 3',
    EPLAN_PROJECT_STRUCTURE_L4_KEY: 'Project Structure Level 4',
    EPLAN_PROJECT_STRUCTURE_L5_KEY: 'Project Structure Level 5',
    EPLAN_PROJECT_STRUCTURE_L6_KEY: 'Project Structure Level 6',
    EPLAN_PROJECT_STRUCTURE_L7_KEY: 'Project Structure Level 7',
    EPLAN_PROJECT_STRUCTURE_L8_KEY: 'Project Structure Level 8',
    EPLAN_PROJECT_STRUCTURE_L9_KEY: 'Project Structure Level 9',
    EPLAN_PROJECT_STRUCTURE_L10_KEY: 'Project Structure Level 10',
    EPLAN_PROJECT_STRUCTURE_L11_KEY: 'Project Structure Level 11',

    # Additional Object Types
    EPLAN_OBJECT_TYPE_116_KEY: 'Object Type 116 Container',
    EPLAN_OBJECT_TYPE_155_KEY: 'Object Type 155 Container',
    EPLAN_OBJECT_TYPE_219_KEY: 'Object Type 219 Container',
    EPLAN_OBJECT_TYPE_256_KEY: 'Object Type 256 Container',

    # Section Definitions
    EPLAN_SECTION_167_FIELD_KEY: 'Section 167 Field Definition',
    EPLAN_SECTION_39_DEFINITION_KEY: 'Section 39 Object Definition',
    EPLAN_SECTION_40_DEFINITION_KEY: 'Section 40 Object Definition',
    EPLAN_SECTION_54_PROPERTIES_KEY: 'Section 54 Properties',

    # Form Attributes
    EPLAN_FORM_ATTRIBUTE_1402_KEY: 'Form Mounting Location',
    EPLAN_FORM_ATTRIBUTE_1403_KEY: 'Form Position Data',
    EPLAN_FORM_ATTRIBUTE_1404_KEY: 'Form Line Style',
    EPLAN_FORM_ATTRIBUTE_1405_KEY: 'Form Configuration String',
    EPLAN_FORM_ATTRIBUTE_1406_KEY: 'Form Attribute 1406',
    EPLAN_FORM_ATTRIBUTE_1407_KEY: 'Form Attribute 1407',
    EPLAN_FORM_ATTRIBUTE_1409_KEY: 'Form Timestamp',
    EPLAN_FORM_ATTRIBUTE_1411_KEY: 'Form Attribute 1411',
    EPLAN_FORM_ATTRIBUTE_1412_KEY: 'Form Page Range',
    EPLAN_FORM_ATTRIBUTE_1414_KEY: 'Form Page Count',
    EPLAN_FORM_ATTRIBUTE_1415_KEY: 'Form Reference',
    EPLAN_FORM_ATTRIBUTE_1416_KEY: 'Form Attribute 1416',
    EPLAN_FORM_ATTRIBUTE_1417_KEY: 'Form Structure References',
    EPLAN_FORM_ATTRIBUTE_1418_KEY: 'Form Scale Factor',

    # High-priority missing attribute mappings
    EPLAN_ATTRIBUTE_1001_KEY: 'Attribute 1001',
    EPLAN_ATTRIBUTE_1101_KEY: 'Attribute 1101',
    EPLAN_ATTRIBUTE_1105_KEY: 'Object Configuration',
    EPLAN_ATTRIBUTE_1106_KEY: 'Object Property',
    EPLAN_ATTRIBUTE_1108_KEY: 'Object State',
    EPLAN_ATTRIBUTE_1306_KEY: 'Display Attribute',
    EPLAN_ATTRIBUTE_1308_KEY: 'Visual Property',
    EPLAN_ATTRIBUTE_1317_KEY: 'Layout Attribute',
    EPLAN_ATTRIBUTE_1331_KEY: 'Position Data',
    EPLAN_ATTRIBUTE_1348_KEY: 'Reference Attribute',
    EPLAN_ATTRIBUTE_1351_KEY: 'Connection Attribute',
    EPLAN_ATTRIBUTE_1352_KEY: 'Connection State',
    EPLAN_ATTRIBUTE_1355_KEY: 'Connection Property',
    EPLAN_ATTRIBUTE_1356_KEY: 'Connection Data',
    EPLAN_ATTRIBUTE_1357_KEY: 'Connection Reference',
    EPLAN_ATTRIBUTE_1358_KEY: 'Connection Flag',
    EPLAN_ATTRIBUTE_1359_KEY: 'Connection Type',
    EPLAN_ATTRIBUTE_1365_KEY: 'Terminal Attribute',
    EPLAN_ATTRIBUTE_1366_KEY: 'Terminal State',
    EPLAN_ATTRIBUTE_1367_KEY: 'Terminal Property',
    EPLAN_ATTRIBUTE_1368_KEY: 'Terminal Data',
    EPLAN_ATTRIBUTE_1370_KEY: 'Terminal Flag',
    EPLAN_ATTRIBUTE_1380_KEY: 'Device Attribute',
    EPLAN_ATTRIBUTE_1381_KEY: 'Device State',
    EPLAN_ATTRIBUTE_1383_KEY: 'Device Property',

    # Additional property mappings
    EPLAN_PROPERTY_10002_KEY: 'Project Configuration 2',
    EPLAN_PROPERTY_10003_KEY: 'Project Setting 3',
    EPLAN_PROPERTY_10010_KEY: 'Project Data 10',
    EPLAN_PROPERTY_10011_KEY: 'Project Flag 11',
    EPLAN_PROPERTY_10012_KEY: 'Project Property 12',
    EPLAN_PROPERTY_10013_KEY: 'Project State 13',
    EPLAN_PROPERTY_10014_KEY: 'Project Reference 14',
    EPLAN_PROPERTY_10015_KEY: 'Project Attribute 15',
    EPLAN_PROPERTY_10016_KEY: 'Project Value 16',
    EPLAN_PROPERTY_10017_KEY: 'Project Setting 17',
}
